// Auto-generated by scripts/sync-dapp.mjs — do not edit manually.
// Run `make sync-dapp` or re-deploy to refresh.

// Note: some entries (e.g. AdminEta) are non-address values; use Record<string, string>.
export const ADDRESSES: Record<number, Record<string, string>> = {
	31337: {
		Treasury: "0x0165878A594ca255338adfa4d48449f69242Eb8F",
		TimeLock: "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
		WerewolfToken: "0x610178dA211FEF7D417bC0e6FeD39F05609AD788",
		Staking: "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
		LPStaking: "0x0B306BF915C4d645ff596e518fAf3F9669b97016",
		DAO: "0x3Aa5ebB10DC797CAC828524e59A333d0A371443c",
		TokenSale: "0x59b670e9fA9D0A427751Af201D676719a970857b",
		USDT: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
		CompaniesHouse: "0x4A679253410272dd5232B3Ff7cF5dbB88f295319",
	},
	84532: {
		Treasury: "0x91CDeB15207410F0018e1dEd776bb17CDD31B237",
		TimeLock: "0xf1FEd640fd81b99bc82F09959354938b364e1A9c",
		WerewolfToken: "0xe89c657177a67b860C15837441317d78dEE87cEC",
		Staking: "0x78cB9Ae279F6b14842e2A6a2B4D9aAc9BA23b6BC",
		LPStaking: "0x15982FDca6fEE76B675CF8ad0e3F3c4c148BAb52",
		DAO: "0x7EbCDc2141AAfE4fA95F198839555f9249647B6C",
		TokenSale: "0x77dAbbEF71D6D7561d91c0F2A439F7FCeE521b0F",
		USDT: "0x33F61ff61be4A67Ad21D73dC679628C70AfCD1A8",
		CompaniesHouse: "0x3Ff2FA68dc3c0233CFdDA8173634A68CA061f207",
		CompanyVaultImpl: "0xAA6b671b5D9859231934Fea05703D81101f97390",
		AaveUSDT: "0xba50Cd2A20f6DA35D788639E581bca8d0B5d4D5f",
		AavePool: "0x8bAB6d1b75f19e9eD9fCe8b9BD338844fF79aE27",
		USDC: "0xba50Cd2A20f6DA35D788639E581bca8d0B5d4D5f",
	},
	11155111: {
		Treasury: "0x59B2B9B1a4FA2c0a8Ea9094D8076866b9E90Eda2",
		TimeLock: "0x544Bc3A2Ae6B0bBC2A361Ce40676841F57aA7377",
		WerewolfToken: "0x3C4a6E74aB45E2CD7f16Cfd583de479EAE0dab97",
		Staking: "0x5B385F8f51a21E5dA28e39128cc65a54396a4eC3",
		LPStaking: "0x945265470c057193835BE31480278B9Bbc75A40A",
		DAO: "0x8c1751b9C65f2a56b00D4bd10e875fc9b750Ac01",
		TokenSale: "0xf3eEa30AB01000E6FCdD3140b5f536178de1e6Ff",
		USDT: "0x8605AAcE6C0e1772F3e59D9D858375843fd26945",
		CompaniesHouse: "0x1fFF8d94aA50Bb81C2b35519d7dD22D67F2D953E",
		CompanyVaultImpl: "0x92D67c3019480F4b7752b06AEd5fC46b14D6751E",
		AaveUSDT: "0x94a9D9AC8a22534E3FaCa9F4e7F2E2cf85d5E4C8",
		AavePool: "0x6Ae43d3271ff6888e7Fc43Fd7321a503ff738951",
		USDC: "0x94a9D9AC8a22534E3FaCa9F4e7F2E2cf85d5E4C8",
	},
};

/** Returns a contract address (0x…) for the given chain, or undefined if not configured. */
export function getAddress(
	chainId: number | undefined,
	name: string,
): `0x${string}` | undefined {
	if (!chainId) return undefined;
	const val = ADDRESSES[chainId]?.[name];
	if (!val || !val.startsWith('0x')) return undefined;
	return val as `0x${string}`;
}
