// Auto-generated by scripts/sync-dapp.mjs — do not edit manually.
// Run `make sync-dapp` or re-deploy to refresh.

// Note: some entries (e.g. AdminEta) are non-address values; use Record<string, string>.
export const ADDRESSES: Record<number, Record<string, string>> = {
	31337: {
		Treasury: "0x0165878A594ca255338adfa4d48449f69242Eb8F",
		TimeLock: "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
		WerewolfToken: "0x610178dA211FEF7D417bC0e6FeD39F05609AD788",
		Staking: "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
		LPStaking: "0x0B306BF915C4d645ff596e518fAf3F9669b97016",
		DAO: "0x3Aa5ebB10DC797CAC828524e59A333d0A371443c",
		TokenSale: "0x59b670e9fA9D0A427751Af201D676719a970857b",
		USDT: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
		CompaniesHouse: "0x4A679253410272dd5232B3Ff7cF5dbB88f295319",
	},
	84532: {
		Treasury: "0xe719F37784fA4C89fd04616Ee21db3E54fd9ef70",
		TimeLock: "0x44d4F41A62F7bF71fcE3433E0676973609bB1fa8",
		WerewolfToken: "0xDA0bb7255Ec44Bb2EA5933E85F1Aa63Eb9583E42",
		Staking: "0x5C20C62FeA01C18104a1D638cEbb66AB0c2F218b",
		LPStaking: "0xF4DF3BF8BED5dd2c3Fb69Fe5816AC472c26F7Fb7",
		DAO: "0xa6BDfa59EcE7cA75a0ad756F4D28298C595d9955",
		TokenSale: "0x3182DfA6b616A238e13e0bc4Ebe10710e12282cd",
		USDT: "0xC0580D5FcC5937bE99db976AD0b56cCe43dc307E",
		CompaniesHouse: "0x9B18B7F51A0804FC3822B81689d882C0f32521A3",
		CompanyVaultImpl: "0x3d63869E5b65CB2cBCD510db49fE8c47d5dadbbe",
		AaveUSDT: "0xba50Cd2A20f6DA35D788639E581bca8d0B5d4D5f",
		AavePool: "0x8bAB6d1b75f19e9eD9fCe8b9BD338844fF79aE27",
		USDC: "0xba50Cd2A20f6DA35D788639E581bca8d0B5d4D5f",
	},
	11155111: {
		Treasury: "0x2AA8dC42AF7E3009E172fff4661Bc9A7A5645Dcb",
		TimeLock: "0x2d7BeCF9B54a93aAE1f787A65419687D02bE0049",
		WerewolfToken: "0xa7C8ECc541F104b1f5826b50eb46AD32AFc3E84E",
		Staking: "0x4CA4bc25A362aCb6e8F8e5d15D2e7d9e642e7635",
		LPStaking: "0xA486E73099B791D43E39DC1b260494891C335941",
		DAO: "0x1020bC323f3b17E8528f09795699d95E1eA89Db7",
		TokenSale: "0x68c22c0F46B49339DD4F5415D001c3E7096c7Cb6",
		USDT: "0x7Eb9317A2c332Ab3799CD6CEd77f35EE0cB16f68",
		CompaniesHouse: "0x4a0695015062BeaF125a95fB86A68639b635d268",
		CompanyVaultImpl: "0xb9e244083c78B03162E83Cf28915c6F0aB4077Bf",
		AaveUSDT: "0x94a9D9AC8a22534E3FaCa9F4e7F2E2cf85d5E4C8",
		AavePool: "0x6Ae43d3271ff6888e7Fc43Fd7321a503ff738951",
		USDC: "0x94a9D9AC8a22534E3FaCa9F4e7F2E2cf85d5E4C8",
	},
};

/** Returns a contract address (0x…) for the given chain, or undefined if not configured. */
export function getAddress(
	chainId: number | undefined,
	name: string,
): `0x${string}` | undefined {
	if (!chainId) return undefined;
	const val = ADDRESSES[chainId]?.[name];
	if (!val || !val.startsWith('0x')) return undefined;
	return val as `0x${string}`;
}
