// Auto-generated by scripts/sync-dapp.mjs — do not edit manually.
// Run `make sync-dapp` or re-deploy to refresh.

// Note: some entries (e.g. AdminEta) are non-address values; use Record<string, string>.
export const ADDRESSES: Record<number, Record<string, string>> = {
	31337: {
		Treasury: "0x0165878A594ca255338adfa4d48449f69242Eb8F",
		TimeLock: "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
		WerewolfToken: "0x610178dA211FEF7D417bC0e6FeD39F05609AD788",
		Staking: "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
		LPStaking: "0x0B306BF915C4d645ff596e518fAf3F9669b97016",
		DAO: "0x3Aa5ebB10DC797CAC828524e59A333d0A371443c",
		TokenSale: "0x59b670e9fA9D0A427751Af201D676719a970857b",
		USDT: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
		CompaniesHouse: "0x4A679253410272dd5232B3Ff7cF5dbB88f295319",
	},
	84532: {
		Treasury: "0x60074e89ad4d88EECc7231f89d01f8AA4EBaC5aF",
		TimeLock: "0xC0590B03Aa1D93F450089e98e32c449e1848e4DC",
		WerewolfToken: "0xf7355f6d69029cE67FCF8AE24f33464f68fe5cb5",
		Staking: "0x18Eb8106aA6C4F3399Df22329276FaDaA1d12A99",
		LPStaking: "0x446087C18CbDfec689a22eB90E00E43aee6f41Ce",
		DAO: "0xF583B4FEFddED2Ab2CbCF2e458Df809ab82131B8",
		TokenSale: "0x7F5061a5878391B253717A8e066fb5aA27008d09",
		USDT: "0x7d8aB118328E2Ef764224d633580615d5f971B89",
		CompaniesHouse: "0xf520A741c290C4d0092713E680d8511D74F88d2b",
		CompanyVaultImpl: "0x7660fF41D692843dddb62602f0EFCF425c27d72B",
		AaveUSDT: "0xba50Cd2A20f6DA35D788639E581bca8d0B5d4D5f",
		AavePool: "0x8bAB6d1b75f19e9eD9fCe8b9BD338844fF79aE27",
		USDC: "0xba50Cd2A20f6DA35D788639E581bca8d0B5d4D5f",
	},
	11155111: {
		Treasury: "0xDEf2a69Fc506E5ef2aAca0EF2194801116E22431",
		TimeLock: "0xc0774E3b247fCbDbf7AF4856c99f885F27788b83",
		WerewolfToken: "0xFDdFec5A16e8e0dAE3b195Ccb9Cbe2c0775931B3",
		Staking: "0x6eb0e9b5A228755Ce9a614DC15a1DAb82A9824AC",
		LPStaking: "0x04a0C736FDAa2EaAa54D15C609B1D0163E2d1e14",
		DAO: "0xA2141d87E5B23F13B4115208aB25b6b2e922a76f",
		TokenSale: "0xAbF02538A6CE5f28268F98c4978064bda8eDB1d9",
		USDT: "0x7778232806698977250c969CE74e5173F76F42bf",
		CompaniesHouse: "0x8bd2acDc496600b107B72249aCe22e68F90F2A56",
		CompanyVaultImpl: "0xb1e4936bd24AeBbaD64cB3D94ED0D8D0cE0BaFf2",
		AaveUSDT: "0x94a9D9AC8a22534E3FaCa9F4e7F2E2cf85d5E4C8",
		AavePool: "0x6Ae43d3271ff6888e7Fc43Fd7321a503ff738951",
		USDC: "0x94a9D9AC8a22534E3FaCa9F4e7F2E2cf85d5E4C8",
	},
};

/** Returns a contract address (0x…) for the given chain, or undefined if not configured. */
export function getAddress(
	chainId: number | undefined,
	name: string,
): `0x${string}` | undefined {
	if (!chainId) return undefined;
	const val = ADDRESSES[chainId]?.[name];
	if (!val || !val.startsWith('0x')) return undefined;
	return val as `0x${string}`;
}
