#!/usr/bin/env node
/**
 * scripts/sync-dapp.mjs
 *
 * Syncs contract addresses and ABIs from Foundry build output into the dapp.
 * Runs automatically after `make deploy-local` / `make deploy-sepolia`,
 * or manually via `make sync-dapp`.
 *
 * What it does:
 *   1. Parses script/output/deployed-addresses.txt  →  new addresses for the deployed chain
 *   2. Reads dapp/src/contracts/addresses.ts         →  preserves addresses for other chains
 *   3. Merges and regenerates addresses.ts
 *   4. Extracts .abi from out/{Contract}.sol/{Contract}.json
 *      and writes dapp/src/contracts/abis/{name}.ts
 *
 * erc20.ts is manually curated and is intentionally excluded.
 */

import { readFileSync, writeFileSync, existsSync, copyFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// ── ABI contract map ───────────────────────────────────────────────────────
// Maps Foundry output → dapp ABI TypeScript file.
// erc20.ts is a hand-written subset of the ERC20 ABI and is excluded.
const ABI_MAP = [
	{ sol: 'DAO.sol',             contract: 'DAO',             exportName: 'daoABI',           file: 'dao.ts' },
	{ sol: 'WerewolfTokenV1.sol', contract: 'WerewolfTokenV1', exportName: 'werewolfTokenABI', file: 'werewolfToken.ts' },
	{ sol: 'Staking.sol',         contract: 'Staking',          exportName: 'stakingABI',        file: 'staking.ts' },
	{ sol: 'TokenSale.sol',       contract: 'TokenSale',        exportName: 'tokenSaleABI',      file: 'tokenSale.ts' },
	{ sol: 'LPStaking.sol',       contract: 'LPStaking',        exportName: 'lpStakingABI',      file: 'lpStaking.ts' },
];

// ── Step 1: Parse deployed-addresses.txt ──────────────────────────────────
const addressesTxtPath = resolve(ROOT, 'script/output/deployed-addresses.txt');

if (!existsSync(addressesTxtPath)) {
	console.error(`[sync-dapp] ERROR: ${addressesTxtPath} not found. Run a deploy first.`);
	process.exit(1);
}

const rawTxt = readFileSync(addressesTxtPath, 'utf-8').trim();
let deployedChainId = null;
const deployedAddrs = {};

for (const line of rawTxt.split('\n')) {
	const colonIdx = line.indexOf(':');
	if (colonIdx === -1) continue;
	const key   = line.slice(0, colonIdx).trim();
	const value = line.slice(colonIdx + 1).trim();
	if (key === 'Chain ID') {
		deployedChainId = parseInt(value, 10);
	} else {
		deployedAddrs[key] = value;
	}
}

if (!deployedChainId) {
	console.error('[sync-dapp] ERROR: Could not parse Chain ID from deployed-addresses.txt');
	process.exit(1);
}

console.log(`[sync-dapp] Deployed chain: ${deployedChainId} (${Object.keys(deployedAddrs).length} contracts)`);

// ── Step 2: Read existing addresses.ts, extract all chain entries ──────────
const addressesTsPath = resolve(ROOT, 'dapp/src/contracts/addresses.ts');
const allChains = {}; // { [chainId]: { ContractName: '0x...' } }

if (existsSync(addressesTsPath)) {
	const existing = readFileSync(addressesTsPath, 'utf-8');
	// Match each numeric chain block:  31337: { ... }
	const chainBlockRe = /(\d+):\s*\{([^}]+)\}/g;
	const addrLineRe   = /(\w+):\s*"(0x[0-9a-fA-F]+)"/g;
	let chainMatch;
	while ((chainMatch = chainBlockRe.exec(existing)) !== null) {
		const cid   = parseInt(chainMatch[1], 10);
		const block = chainMatch[2];
		allChains[cid] = {};
		let addrMatch;
		while ((addrMatch = addrLineRe.exec(block)) !== null) {
			allChains[cid][addrMatch[1]] = addrMatch[2];
		}
	}
}

// ── Step 3: Merge deployed addresses ──────────────────────────────────────
allChains[deployedChainId] = deployedAddrs;

// ── Step 4: Regenerate addresses.ts ───────────────────────────────────────
const chainBlocks = Object.entries(allChains)
	.sort(([a], [b]) => Number(a) - Number(b))
	.map(([cid, addrs]) => {
		const lines = Object.entries(addrs)
			.map(([name, addr]) => `\t\t${name}: "${addr}",`)
			.join('\n');
		return `\t${cid}: {\n${lines}\n\t},`;
	})
	.join('\n');

const addressesTsContent =
`// Auto-generated by scripts/sync-dapp.mjs — do not edit manually.
// Run \`make sync-dapp\` or re-deploy to refresh.

// Note: some entries (e.g. AdminEta) are non-address values; use Record<string, string>.
export const ADDRESSES: Record<number, Record<string, string>> = {
${chainBlocks}
};

/** Returns a contract address (0x…) for the given chain, or undefined if not configured. */
export function getAddress(
	chainId: number | undefined,
	name: string,
): \`0x\${string}\` | undefined {
	if (!chainId) return undefined;
	const val = ADDRESSES[chainId]?.[name];
	if (!val || !val.startsWith('0x')) return undefined;
	return val as \`0x\${string}\`;
}
`;

writeFileSync(addressesTsPath, addressesTsContent, 'utf-8');
console.log(`[sync-dapp] Updated ${addressesTsPath}`);

// ── Step 5: Generate ABI TypeScript files ─────────────────────────────────
for (const { sol, contract, exportName, file } of ABI_MAP) {
	const jsonPath = resolve(ROOT, `out/${sol}/${contract}.json`);
	if (!existsSync(jsonPath)) {
		console.warn(`[sync-dapp] WARN: ${jsonPath} not found — skipping ${file} (run \`forge build\` first)`);
		continue;
	}
	const { abi } = JSON.parse(readFileSync(jsonPath, 'utf-8'));
	const outPath = resolve(ROOT, `dapp/src/contracts/abis/${file}`);
	const content = `// Auto-generated by scripts/sync-dapp.mjs — do not edit manually.\nexport const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
	writeFileSync(outPath, content, 'utf-8');
	console.log(`[sync-dapp] Updated ${outPath}`);
}

// ── Step 6: Sync white paper ───────────────────────────────────────────────
const whitepaperSrc = resolve(ROOT, 'white-paper.md');
const whitepaperDst = resolve(ROOT, 'dapp/public/whitepaper.md');
if (existsSync(whitepaperSrc)) {
	copyFileSync(whitepaperSrc, whitepaperDst);
	console.log(`[sync-dapp] Synced white-paper.md → dapp/public/whitepaper.md`);
} else {
	console.warn('[sync-dapp] WARN: white-paper.md not found at root — skipping whitepaper sync');
}

console.log('[sync-dapp] Done.');
